name: "CI"

on:
  pull_request:
  push:
    branches: [ 'master' ]
jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
      - uses: actions/checkout@v4
      - name: Environment
        run: cp .env.example .env
      - uses: ramsey/composer-install@v3
      - name: PHP CS Fixer
        run: composer style:check

  phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
      - uses: actions/checkout@v4
      - name: Environment
        run: cp .env.example .env
      - uses: ramsey/composer-install@v3
      - name: PHPStan
        run: composer phpstan

  tests:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:17.2-alpine3.20
        env:
          POSTGRES_DB: app
          POSTGRES_USER: app
          POSTGRES_PASSWORD: app
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
    env:
      DATABASE_URL: postgresql://app:app@127.0.0.1:5432/app?serverVersion=17&charset=utf8
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: pdo_pgsql
      - uses: actions/checkout@v4
      - name: Environment
        run: cp .env.example .env
      - uses: ramsey/composer-install@v3
      - name: Preparing
        run: composer test:prepare
      - name: Tests
        run: composer test
